Makes Path `Home` Symbol Customizable
JanDeDobbeleer/oh-my-posh2 pull request #165
Opened 2019-09-05 13:51 UTC by brucificus

The makes the tilde (`~`) used in home-relative paths be replaceable by themes.

2019-11-02 19:40 UTC, JanDeDobbeleer requested changes

2019-11-02 19:40 UTC, JanDeDobbeleer commented on Helpers/Prompt.Tests.ps1
> +        HomeSymbol                     = '*'
Can you set this default value to `~`? That way it will stay consistent with current configs.

2019-11-06 14:46 UTC, FGS-BMarkham commented on Helpers/Prompt.Tests.ps1
> +        HomeSymbol                     = '*'
My intent in deviating this value for the tests was to make sure the test verifies that the code under test respects the theme setting - and in turn does not, for example, have a regression wherein the implementation hard-codes the tilde.

What are your thoughts on such?

FWIW, my testing habits are very biased towards keeping tests from incidentally having or acquiring false positives. I might just be being overzealous with such.

2019-11-06 14:48 UTC, brucificus commented on Helpers/Prompt.Tests.ps1
> +        HomeSymbol                     = '*'
My intent in deviating this value for the tests was to make sure the test verifies that the code under test respects the theme setting - and in turn does not, for example, have a regression wherein the implementation hard-codes the tilde.

What are your thoughts on such?

FWIW, my testing habits are very biased towards keeping tests from incidentally having or acquiring false positives. I might just be being overzealous with such.

2019-11-07 09:33 UTC, JanDeDobbeleer commented on Helpers/Prompt.Tests.ps1
> +        HomeSymbol                     = '*'
Ah, no my bad I missed the fact this was added in the tests.

2019-11-07 09:33 UTC, JanDeDobbeleer approved these changes

2019-11-07 09:34 UTC, JanDeDobbeleer commented
Can you rebase your branch on the latest master so the conflicts can be resolved?

2019-11-07 13:36 UTC, brucificus commented
👍 Rebased.

2019-11-10 14:12 UTC, merged