New functions and tweaks
JanDeDobbeleer/oh-my-posh2 pull request #48
Opened 2017-08-11 08:18 UTC by MartinSGill

- Added Get-Theme function to list available themes
- Added Show-ThemeSymbols function to list defined symbols
- Allow themes to be re-loaded by Set-Theme
- Made Show-ThemeColors implementation more generic
- ArgumentCompleter now re-uses Get-Theme function

2017-08-11 12:26 UTC, JanDeDobbeleer requested changes

2017-08-11 12:26 UTC, JanDeDobbeleer commented on oh-my-posh.psd1
> +#ModuleVersion = '0.0.0'
This needs to be reset or it won't be build :-)

2017-08-11 12:26 UTC, JanDeDobbeleer commented on oh-my-posh.psm1
> +    $sl.Colors.Keys | Sort-Object | ForEach-Object { Write-ColorPreview -text ("{0,-35}" -f $_ ) -color $sl.Colors[$_] }
Makes a lot more sense, I was mainly lazy :-)

2017-08-11 12:26 UTC, JanJoris commented on oh-my-posh.psm1
> +    Set-Prompt;
Any specific reason to add `;` here?

2017-08-12 11:01 UTC, MartinSGill commented on oh-my-posh.psm1
> +    Set-Prompt;
Left over from some debugging code. I suspect.

2017-08-12 11:02 UTC, MartinSGill commented on oh-my-posh.psd1
> +#ModuleVersion = '0.0.0'
It's commented out.. but I'll remove it all the same.

2017-08-14 20:12 UTC, JanDeDobbeleer approved these changes
Code wise it looks ok, I just need to be able to validate this on a Windows machine (short of one ATM).

2017-08-14 20:12 UTC, JanJoris commented on oh-my-posh.psd1
> +#ModuleVersion = '0.0.0'
Cool didn't see that.

2017-08-17 06:30 UTC, JanJoris commented
Update: I'll have access to my Windows setup on Monday. If everything works as advertised, I'll deploy immediately. And I'll make sure to create a VM setup.

2017-08-17 13:49 UTC, MartinSGill commented
I've got a windows setup, does that count? :)

2017-08-17 19:00 UTC, JanJoris commented
> I've got a windows setup, does that count? :)

Well, as much as I'd love to put all my trust in strangers on the internet, I really want to check everything at least once myself for now :-)

2017-08-29 12:58 UTC, merged